reports = [
    {
        'id': 1,
        'name': 'investment 1',
        'description': 'This is my first investment report',
        'data': {
            'insightsData': {
                "Price per meter": 8500,
                "Loan to cost": 9600,
                "Loan to value": 4400,
                "Renovation expenses": 6000,
                "Purchase additional transactions cost": 4900,
                "Purchase tax": 8400,
                "Closing costs": 5300,
                "Broker purchase cost": 5500,
                "Monthly operating expenses": 8900,
                "Cash on cash": 2000,
                "Net Yearly Cash Flow": 8500,
                "Net Monthly Cash Flow": 4200,
                "Yearly IRR": 8700,
                "Annual rent income": 7900,
                "ROI": 970,
                "Monthly NOI": 9800,
                "Annual NOI": 7300,
                "Monthly rental property taxes": 6700,
                "Annual rental property taxes": 7000,
                "Cap rate": 6000,
                "Gross yield": 9500,
                "Monthly insurances expenses": 4600,
                "Annual insurances expenses": 1700,
                "Monthly maintenance and repairs": 9600,
                "Annual maintenance and repairs": 4600,
                "Monthly vacancy cost": 6500,
                "Annual vacancy cost": 5800,
                "Estimated sale price": 4800,
                "Selling expenses": 8600,
                "Sale proceeds": 2400,
                "Total revenue": 2100,
                "Annual revenue distribution": 4300,
                "Annual operating expenses": 4200,
                "Annual cash flow": 2100,
                "Mortgage remain balance in exit": 2800,
                "Constructor index linked compensation": 7000,
                "Total expenses": 3100,
                "Equity needed for purchase": 2800,
                "Contractor payments": 3400,
                "Annual expenses distribution": 2900,
                "Monthly property management fees": 8200,
                "Annual property management fees": 8900,
                "Net profit": 1800,
                "Capital gain tax": 9800
            },
            'investmentData': {
                'appraiser_cost': 500,
                'lawyer_cost': 1000,
                'escort_costs': 200,
                'additional_transaction_costs_dic': {'tax': 1500, 'fee': 300},
                'renovation_expenses_dic': {'painting': 1000, 'flooring': 1500},
                'furniture_cost': 3000,
                'broker_purchase_percentage': 2,
                'broker_rent_percentage': 1,
                'broker_sell_percentage': 3,
                'vacancy_percentage': 0.1,
                'annual_maintenance_cost_percentage': 0.05,
                'annual_life_insurance_cost': 500,
                'annual_house_insurance_cost': 600,
                'equity_required_by_percentage': 20,
                'management_fees_percentage': 5,
                'years_to_exit': 5,
                'average_interest_in_exit': 3.5
            },
            'investorData': {
                'net_monthly_income': 5000,
                'total_debt_payment': 1000,
                'RealEstateInvestmentType': 'apartment',
                'total_available_equity': 200000,
                'gross_rental_income': 1500
            },
            'propertyData': {
                'purchase_price': 300000,
                'monthly_rent_income': 1500,
                'square_meters': 100,
                'parking_spots': 2,
                'warehouse': True,
                'balcony_square_meter': 10,
                'after_repair_value': 350000,
                'annual_appreciation_percentage': 2
            },
            'mortgageData': {
                'mortgage_advisor_cost': 500,
                'interest_rate': 3.5,
                'num_payments': 360,
                'initial_loan_amount': 240000,
                'interest_only_period': 5
            },
            'otherData': {
                'years_until_key_reception': 2,
                'contractor_payment_distribution': [20, 30, 50],
                'construction_input_index_annual_growth': 3
            }
        }
    },
{
        'id': 2,
        'name': 'investment 2',
        'description': 'This is my second investment report',
        'data': {
            'insightsData': {
                "Price per meter": 8500,
                "Loan to cost": 9600,
                "Loan to value": 4400,
                "Renovation expenses": 6000,
                "Purchase additional transactions cost": 4900,
                "Purchase tax": 8400,
                "Closing costs": 5300,
                "Broker purchase cost": 5500,
                "Monthly operating expenses": 8900,
                "Cash on cash": 2000,
                "Net Yearly Cash Flow": 8500,
                "Net Monthly Cash Flow": 4200,
                "Yearly IRR": 8700,
                "Annual rent income": 7900,
                "ROI": 970,
                "Monthly NOI": 9800,
                "Annual NOI": 7300,
                "Monthly rental property taxes": 6700,
                "Annual rental property taxes": 7000,
                "Cap rate": 6000,
                "Gross yield": 9500,
                "Monthly insurances expenses": 4600,
                "Annual insurances expenses": 1700,
                "Monthly maintenance and repairs": 9600,
                "Annual maintenance and repairs": 4600,
                "Monthly vacancy cost": 6500,
                "Annual vacancy cost": 5800,
                "Estimated sale price": 4800,
                "Selling expenses": 8600,
                "Sale proceeds": 2400,
                "Total revenue": 2100,
                "Annual revenue distribution": 4300,
                "Annual operating expenses": 4200,
                "Annual cash flow": 2100,
                "Mortgage remain balance in exit": 2800,
                "Constructor index linked compensation": 7000,
                "Total expenses": 3100,
                "Equity needed for purchase": 2800,
                "Contractor payments": 3400,
                "Annual expenses distribution": 2900,
                "Monthly property management fees": 8200,
                "Annual property management fees": 8900,
                "Net profit": 1800,
                "Capital gain tax": 9800
            },
            'investmentData': {
                'appraiser_cost': 500,
                'lawyer_cost': 1000,
                'escort_costs': 200,
                'additional_transaction_costs_dic': {'tax': 1500, 'fee': 300},
                'renovation_expenses_dic': {'painting': 1000, 'flooring': 1500},
                'furniture_cost': 3000,
                'broker_purchase_percentage': 2,
                'broker_rent_percentage': 1,
                'broker_sell_percentage': 3,
                'vacancy_percentage': 0.1,
                'annual_maintenance_cost_percentage': 0.05,
                'annual_life_insurance_cost': 500,
                'annual_house_insurance_cost': 600,
                'equity_required_by_percentage': 20,
                'management_fees_percentage': 5,
                'years_to_exit': 5,
                'average_interest_in_exit': 3.5
            },
            'investorData': {
                'net_monthly_income': 5000,
                'total_debt_payment': 1000,
                'RealEstateInvestmentType': 'apartment',
                'total_available_equity': 200000,
                'gross_rental_income': 1500
            },
            'propertyData': {
                'purchase_price': 300000,
                'monthly_rent_income': 1500,
                'square_meters': 100,
                'parking_spots': 2,
                'warehouse': True,
                'balcony_square_meter': 10,
                'after_repair_value': 350000,
                'annual_appreciation_percentage': 2
            },
            'mortgageData': {
                'mortgage_advisor_cost': 500,
                'interest_rate': 3.5,
                'num_payments': 360,
                'initial_loan_amount': 240000,
                'interest_only_period': 5
            },
            'otherData': {
                'years_until_key_reception': 2,
                'contractor_payment_distribution': [20, 30, 50],
                'construction_input_index_annual_growth': 3
            }
        }
    }
]
